#!/bin/sh

# This sleep/wakeup script is meant to be used on a system using r8168 (i.e. ThinkPad E580)
# It reloads ethernet driver when geeting out of suspend.
# On Arch Linux based system, This file shloud be called `hdparm`
# And should be placed in `/usr/lib/systemd/system-sleep`
# Make sure to make it runnable (sudo chmod +x /usr/lib/systemd/system-sleep/hdparm)
#
# This script was found here : https://superuser.com/questions/1065342/wired-ethernet-connection-not-working-after-suspend-on-debian

if [ "${1}" == "pre" ]; then
  # Do the thing you want before suspend here, e.g.:
    sudo modprobe -r r8168
elif [ "${1}" == "post" ]; then    
    sudo modprobe r8168
fi
